# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[CI] "
    labels:
      - "ci-cd"
      - "dependencies"
    groups:
      ci-actions:
        patterns: ["*"]
      
  # Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:             # don't create "java" label (default for gradle ecosystem)
      - "dependencies"
    groups:
      lib-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: "org.mnode.ical4j:ical4j"
        versions: ["4.x"]
