changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Refactoring
      labels:
        - refactoring
    - title: Dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
