name: Blank issue (internal use only)
description: "For internal use (DAVx5 team) only"
body:
- type: markdown
  attributes:
    value: |
      This form is for internal use only and doesn't set the triage label. That means your issue won't be handled properly.
      **Please use one of the other issue templates instead.**"
- type: textarea
  id: body
  attributes:
    label: ""
    description: ""
    placeholder: ""
  validations:
    required: false
