# log instrumented test output to logcat
handlers=at.bitfire.synctools.log.LogcatHandler
.level=ALL
# reduce verbose of some otherwise annoying ical4j messages
net.fortuna.ical4j.data.level=INFO
net.fortuna.ical4j.model.Recur.level=INFO
