/*
 * Copyright © All Contributors. See LICENSE and AUTHORS in the root directory for details.
 */

package at.bitfire.synctools.mapping.davtasks

import android.content.Entity
import at.bitfire.synctools.icalendar.AssociatedTasks
import at.bitfire.synctools.icalendar.withUserAgents
import at.bitfire.synctools.mapping.davtasks.handler.AlarmsHandler
import at.bitfire.synctools.mapping.davtasks.handler.AttachmentsHandler
import at.bitfire.synctools.mapping.davtasks.handler.AttendeesHandler
import at.bitfire.synctools.mapping.davtasks.handler.CategoriesHandler
import at.bitfire.synctools.mapping.davtasks.handler.ClassificationHandler
import at.bitfire.synctools.mapping.davtasks.handler.ColorHandler
import at.bitfire.synctools.mapping.davtasks.handler.CommentsHandler
import at.bitfire.synctools.mapping.davtasks.handler.CompletedHandler
import at.bitfire.synctools.mapping.davtasks.handler.ContactHandler
import at.bitfire.synctools.mapping.davtasks.handler.DavTaskEntityHandler
import at.bitfire.synctools.mapping.davtasks.handler.DescriptionHandler
import at.bitfire.synctools.mapping.davtasks.handler.DueHandler
import at.bitfire.synctools.mapping.davtasks.handler.DurationHandler
import at.bitfire.synctools.mapping.davtasks.handler.GeoHandler
import at.bitfire.synctools.mapping.davtasks.handler.LocationHandler
import at.bitfire.synctools.mapping.davtasks.handler.OrganizerHandler
import at.bitfire.synctools.mapping.davtasks.handler.PercentCompleteHandler
import at.bitfire.synctools.mapping.davtasks.handler.PriorityHandler
import at.bitfire.synctools.mapping.davtasks.handler.RecurrenceFieldsHandler
import at.bitfire.synctools.mapping.davtasks.handler.RelationsHandler
import at.bitfire.synctools.mapping.davtasks.handler.RequestStatusHandler
import at.bitfire.synctools.mapping.davtasks.handler.ResourcesHandler
import at.bitfire.synctools.mapping.davtasks.handler.SequenceHandler
import at.bitfire.synctools.mapping.davtasks.handler.StartTimeHandler
import at.bitfire.synctools.mapping.davtasks.handler.StatusHandler
import at.bitfire.synctools.mapping.davtasks.handler.SummaryHandler
import at.bitfire.synctools.mapping.davtasks.handler.UidHandler
import at.bitfire.synctools.mapping.davtasks.handler.UnknownPropertiesHandler
import at.bitfire.synctools.mapping.davtasks.handler.UrlHandler
import at.bitfire.synctools.storage.davtasks.DavTaskAndExceptions
import at.bitfire.tasks.contract.TaskProperties
import net.fortuna.ical4j.model.component.VToDo
import net.fortuna.ical4j.model.property.ProdId
import java.util.UUID

/**
 * Maps an [Entity] (task row + sub-rows, as stored in the DAVx⁵-hosted tasks provider) back to an
 * iCal4j [VToDo]. Structurally mirrors [at.bitfire.synctools.mapping.tasks.DmfsTaskHandler].
 */
class DavTaskHandler(
    private val prodId: ProdId,
    private val userAgentPackageName: String
) {
    private val entityHandlers = arrayOf<DavTaskEntityHandler>(
        UidHandler(),
        SummaryHandler(),
        SequenceHandler(),
        StartTimeHandler(),
        DueHandler(),
        DurationHandler(),
        DescriptionHandler(),
        LocationHandler(),
        GeoHandler(),
        ColorHandler(),
        UrlHandler(),
        OrganizerHandler(),
        PriorityHandler(),
        ClassificationHandler(),
        StatusHandler(),
        CompletedHandler(),
        PercentCompleteHandler(),
        RecurrenceFieldsHandler(),
        AlarmsHandler(),
        CategoriesHandler(),
        CommentsHandler(),
        RelationsHandler(),
        AttendeesHandler(),
        AttachmentsHandler(),
        ContactHandler(),
        ResourcesHandler(),
        RequestStatusHandler(),
        UnknownPropertiesHandler(),
    )

    /**
     * @param uid           UID of the mapped task
     * @param generatedUid  whether [uid] was generated by [mapToVToDos] (`false`: UID was already present)
     */
    class MappingResult(
        val associatedTasks: AssociatedTasks,
        val uid: String,
        val generatedUid: Boolean
    )

    fun mapToVToDos(taskAndExceptions: DavTaskAndExceptions): MappingResult {
        var generatedUid = false
        val mainValues = taskAndExceptions.main.entityValues
        val uid = mainValues.getAsString(at.bitfire.tasks.contract.Tasks._UID) ?: run {
            val newUid = UUID.randomUUID().toString()
            mainValues.put(at.bitfire.tasks.contract.Tasks._UID, newUid)
            generatedUid = true
            newUid
        }

        val main = mapTask(entity = taskAndExceptions.main, main = taskAndExceptions.main)

        // Exceptions are not yet supported by the mapping code (#2357)
        val exceptions = listOf<VToDo>()

        val mappedTasks = AssociatedTasks(
            main = main,
            exceptions = exceptions,
            prodId = prodId.withUserAgents(listOf(userAgentPackageName))
        )

        return MappingResult(associatedTasks = mappedTasks, uid = uid, generatedUid = generatedUid)
    }

    private fun mapTask(entity: Entity, main: Entity): VToDo {
        val vToDo = VToDo(/* initialise = */ true)
        for (handler in entityHandlers)
            handler.process(from = entity, main = main, to = vToDo)
        return vToDo
    }
}

internal val Entity.NamedContentValues.mimeType: String?
    get() = values.getAsString(TaskProperties.MIMETYPE)
