/*
 * Copyright © All Contributors. See LICENSE and AUTHORS in the root directory for details.
 */

package at.bitfire.synctools.mapping.tasks

import android.content.Entity
import at.bitfire.synctools.icalendar.AssociatedTasks
import at.bitfire.synctools.storage.tasks.TaskAndExceptions
import net.fortuna.ical4j.model.component.VToDo
import org.dmfs.tasks.contract.TaskContract

class DmfsTaskHandler(
    // probably some mapping context here, see AndroidEventHandler
) {

    /**
     * Result of the [mapToVToDos] operation.
     *
     * @param associatedTasks  mapped tasks
     * @param uid              UID of the mapped tasks
     * @param generatedUid     whether [uid] was generated by [mapToVToDos] (*false*: `UID` was already present before mapping)
     */
    class MappingResult(
        val associatedTasks: AssociatedTasks,
        val uid: String,
        val generatedUid: Boolean
    )

    fun mapToVToDos(taskAndExceptions: TaskAndExceptions): MappingResult {
        TODO("Map content provider data (TaskAndExceptions) to VTODOs (AssociatedTasks) + optional generated UID")
        // just like AndroidEventHandler.mapToVEvents
        // uses mapTask()
        // result will be used by TasksSyncManager
    }

    private fun mapTask(entity: Entity, main: Entity): VToDo {
        TODO("Maps a single content-provider task (entity) to iCalendar VTODO")
        // converts "entity", but may use "main" to acquire information like whether the main item is all-day
        // just like AndroidEventHandler.mapEvent()
    }

}

internal val Entity.NamedContentValues.mimeType: String?
    get() = values.getAsString(TaskContract.Properties.MIMETYPE)