/*
 * Copyright © All Contributors. See LICENSE and AUTHORS in the root directory for details.
 */

package at.bitfire.synctools.mapping.tasks

import android.content.Entity
import at.bitfire.synctools.icalendar.AssociatedEvents
import at.bitfire.synctools.storage.calendar.EventAndExceptions
import net.fortuna.ical4j.model.component.VToDo

class DmfsTaskHandler(
    // probably some mapping context here, see AndroidEventHandler
) {

    /**
     * Result of the [mapToVEvents] operation.
     *
     * @param associatedEvents  mapped events
     * @param uid               UID of the mapped events
     * @param generatedUid      whether [uid] was generated by [mapToVEvents] (*false*: `UID` was already present before mapping)
     */
    class MappingResult(
        val associatedEvents: AssociatedEvents,
        val uid: String,
        val generatedUid: Boolean
    )

    fun mapToVEvents(eventAndExceptions: EventAndExceptions): MappingResult {
        TODO("Map content provider data (EventAndExceptions) to VTODOs (AssociatedEvents) + optional generated UID")
        // just like AndroidEventHandler.mapToVEvents
        // uses mapTask()
        // result will be used by TasksSyncManager
    }

    private fun mapTask(entity: Entity, main: Entity): VToDo {
        TODO("Maps a single content-provider task (entity) to iCalendar VTODO")
        // converts "entity", but may use "main" to acquire information like whether the main item is all-day
        // just like AndroidEventHandler.mapEvent()
    }

}