/*
 * Copyright © All Contributors. See LICENSE and AUTHORS in the root directory for details.
 */

package at.bitfire.davdroid.accounts

import android.os.Bundle
import at.bitfire.davdroid.db.DbAccount
import android.accounts.Account as AndroidAccount

/**
 * Uniquely identifies an app account.
 */
sealed interface AccountId

/**
 * A legacy account that is backed by Android's AccountManager.
 */
data class LegacyAccount(val androidAccount: AndroidAccount) : AccountId {
    override fun toString(): String {
        return "${androidAccount.type}/${androidAccount.name}"
    }
}

/**
 * An account that identifies an entry in the accounts' database.
 * @see [at.bitfire.davdroid.db.DbAccount]
 */
data class DbAccount(val account: DbAccount) : AccountId {
    fun toBundle(keyPrefix: String): Bundle = Bundle().apply {
        putLong("${keyPrefix}_id", account.id)
        putString("${keyPrefix}_name", account.name)
    }

    companion object {
        /**
         * Tries to reconstruct an instance of [at.bitfire.davdroid.accounts.DbAccount] from a bundle generated by
         * [at.bitfire.davdroid.accounts.DbAccount.toBundle].
         * @return The `DbAccount` instance if the [bundle] contains valid data, otherwise `null`.
         */
        fun fromBundle(bundle: Bundle, keyPrefix: String): at.bitfire.davdroid.accounts.DbAccount? {
            return DbAccount(
                DbAccount(
                    id = bundle.getLong("${keyPrefix}_id").takeIf { it > 0L } ?: return null,
                    name = bundle.getString("${keyPrefix}_name") ?: return null
                )
            )
        }
    }
}
