/*
 * Copyright © All Contributors. See LICENSE and AUTHORS in the root directory for details.
 */

package at.bitfire.davdroid.accounts

import android.os.Bundle
import at.bitfire.davdroid.db.DbAccount
import android.accounts.Account as AndroidAccount

/**
 * Uniquely identifies an app account.
 */
sealed interface AccountId

/**
 * A legacy account that is backed by Android's AccountManager.
 */
data class LegacyAccount(val androidAccount: AndroidAccount) : AccountId {
    override fun toString(): String {
        return "${androidAccount.type}/${androidAccount.name}"
    }
}

/**
 * An account that identifies an entry in the accounts' database.
 * @see [at.bitfire.davdroid.db.DbAccount]
 */
data class DbAccountId(val account: DbAccount) : AccountId {
    /**
     * Converts this class into a [Bundle], by adding the properties of [account] to a new [Bundle], with each key prefixed with [keyPrefix]:
     * - [DbAccount.id] -> `${keyPrefix}_id`
     * - [DbAccount.name] -> `${keyPrefix}_name`
     * This can then be added to an [android.content.Intent] for example with [android.content.Intent.putExtras].
     */
    fun toBundle(keyPrefix: String): Bundle = Bundle().apply {
        putLong("${keyPrefix}_id", account.id)
        putString("${keyPrefix}_name", account.name)
    }

    companion object {
        /**
         * Tries to reconstruct an instance of [DbAccountId] from a bundle generated by [DbAccountId.toBundle].
         * @return The `DbAccount` instance if the [bundle] contains valid data, otherwise `null`.
         */
        fun fromBundle(bundle: Bundle, keyPrefix: String): DbAccountId? {
            return DbAccountId(
                DbAccount(
                    id = bundle.getLong("${keyPrefix}_id").takeIf { it > 0L } ?: return null,
                    name = bundle.getString("${keyPrefix}_name") ?: return null
                )
            )
        }
    }
}
