/*
 * This file is part of bitfireAT/synctools which is released under GPLv3.
 * Copyright © All Contributors. See the LICENSE and AUTHOR files in the root directory for details.
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package at.bitfire.synctools.mapping.jtx

import android.content.Entity
import at.bitfire.synctools.icalendar.AssociatedComponents
import at.bitfire.synctools.mapping.jtx.handler.DescriptionHandler
import at.bitfire.synctools.mapping.jtx.handler.JtxFieldHandler
import at.bitfire.synctools.storage.jtx.JtxItemAndExceptions
import at.techbee.jtx.JtxContract
import net.fortuna.ical4j.model.Property
import net.fortuna.ical4j.model.component.CalendarComponent
import net.fortuna.ical4j.model.component.VJournal
import net.fortuna.ical4j.model.component.VToDo
import net.fortuna.ical4j.model.property.ProdId
import net.fortuna.ical4j.model.property.RRule
import java.util.UUID

typealias AssociatedItems = AssociatedComponents<CalendarComponent>

/**
 * Mapper from jtx Board item main + data rows to [VJournal] or [VToDo].
 *
 * @param prodId the `PRODID` to use
 */
class JtxItemHandler(
    private val prodId: ProdId
) {
    private val fieldHandlers: Array<JtxFieldHandler> = arrayOf(
        DescriptionHandler()
    )

    /**
     * Maps a jtx Board item with its exceptions to [VJournal] or [VToDo].
     *
     * VJOURNAL and VTODO must have a valid `UID`. So this method generates an UID, if necessary.
     * If an `UID` was generated, it is noted in the result.
     */
    fun mapToCalendarComponents(itemAndExceptions: JtxItemAndExceptions): MappingResult {
        // make sure that main item has a UID
        var generatedUid = false
        val mainValues = itemAndExceptions.main.entityValues
        val uid = mainValues.getAsString(JtxContract.JtxICalObject.UID) ?: run {
            generatedUid = true
            UUID.randomUUID().toString()
        }

        // map main item
        val main = mapItem(
            entity = itemAndExceptions.main,
            main = itemAndExceptions.main
        )

        val rRules = main.getProperties<RRule<*>>(Property.RRULE)
        val exceptions: List<CalendarComponent> = if (rRules.isNotEmpty()) {
            // add exceptions to recurring main item
            itemAndExceptions.exceptions.map { exception ->
                mapItem(
                    entity = exception,
                    main = itemAndExceptions.main
                )
            }
        } else {
            emptyList()
        }

        return MappingResult(
            associatedItems = AssociatedItems(
                main = main,
                exceptions = exceptions,
                prodId = prodId
            ),
            uid = uid,
            generatedUid = generatedUid
        )
    }

    /**
     * Maps data of an item from the jtx Board content provider to [VJournal] or [VToDo].
     *
     * @param entity item row as returned by the jtx Board content provider
     * @param main main item row as returned by the jtx Board content provider
     *
     * @return generated data object
     */
    private fun mapItem(entity: Entity, main: Entity): CalendarComponent {
        val entityComponent = entity.getComponent()
        val mainComponent = main.getComponent()

        require(entityComponent == mainComponent) {
            "'main' and 'entity' need to be of same jtx Board component type"
        }

        val item = when (entityComponent) {
            JtxContract.JtxICalObject.Component.VJOURNAL -> VJournal()
            JtxContract.JtxICalObject.Component.VTODO -> VToDo()
        }

        for (handler in fieldHandlers) {
            handler.process(from = entity, main = main, to = item)
        }

        return item
    }

    private fun Entity.getComponent(): JtxContract.JtxICalObject.Component {
        val componentValue = entityValues.getAsString(JtxContract.JtxICalObject.COMPONENT)
        return JtxContract.JtxICalObject.Component.valueOf(componentValue)
    }

    /**
     * Result of the [mapToCalendarComponents] operation.
     *
     * @param associatedItems mapped items
     * @param uid UID of the mapped items
     * @param generatedUid whether [uid] was generated by [mapToCalendarComponents]
     *   (*false*: `UID` was already present before mapping)
     */
    class MappingResult(
        val associatedItems: AssociatedItems,
        val uid: String,
        val generatedUid: Boolean
    )
}
